puts "The students of Villans Academy"
puts "_____________"
puts "Dr. Hannibal lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex Delarge"
puts "The wicked witch of the west"
puts "Terminator"
puts "Freddy Krueger"
puts "The joker"
puts "Joffret Baratheon"
puts "Norman Bates"
